### ISSUE TITLE
QASM file missing from repo? 

### ISSUE THREAD

**Issue by Qubitium** [Lumorti/Quandoom#1]
I see the large qasm file bundled with compiled linux/window sim but the raw qasm file is not.

**Comment by Lumorti** [comment]
The raw QASM is not on the repo because it is a large file. GitHub releases has a 2GB file limit, whilst within a GitHub repo the file limit is 100MB. The compressed QASM was around 100MB, so I wasn't sure if the repo would allow it, as such I just put in the release.

https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github

**Comment by tsevasa** [comment]
For what it's worth, compressing the QASM file to `.rar` format (using WinRAR) instead of `.zip` reduces the file size to 23MB.

**Comment by Lumorti** [comment]
Oh woah, I didn't expect that there would be so much difference with rar versus zip! Thanks both you, I'll rar it and put it on the repo tonight

**Comment by ilovelinux** [comment]
`.tar.xz` format compression with `-9e` flag is even better.
```sh
$ XZ_OPT=-9 tar cJf quandoom.tar.xz quandoom.qasm 
$ XZ_OPT=-9e tar cJf quandoom-e.tar.xz quandoom.qasm 
$ ls -ohr *.tar.xz
-rw-r--r-- 1 user 20M Sep 30 20:49 quandoom.tar.xz
-rw-r--r-- 1 user 14M Sep 30 17:50 quandoom-e.tar.xz
```
Each time you'll update the compressed file, the old one will be kept into repository history, which will be downloaded during each repository clone. Repository size will increase linearly for each `quandoom.qasm` edit. That's why compression format and levels may be important.

If you want to replace `.rar` format with `.tar.xz` format, you may want to remove `.rar` file from repository history with a force push. This way, you'll avoid to have a useless `.rar` archive in the repository history.

**Comment by Lumorti** [comment]
Good point about the repo history, I'll make sure I force remove it if I change it. And nice find with the tar.xz, for now I'll leave it but if at some point I modify the QASM I'll be sure to tar.xz it instead
